require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/admin/*'
